### PR TITLE
Fix is_on() method

### PR DESCRIPTION
**Pull request by jaysoffian**

### CODE REVIEW

**Comment by aschmidt74** [comment]
excellent! `works4me` **tnx**!
```
[1/10/2022, 12:21:43 AM] [Beamer] Setting projector power: ON
[1/10/2022, 12:21:47 AM] [Beamer] Projector power set to: ON
[1/10/2022, 12:21:48 AM] [Beamer] Returning projector power: ON
```

**Comment by AviatorBimmer** [comment]
Can someone please guide me on how to edit the __init__.py file so I can apply this fix, please?

**Comment by iloveicedgreentea** [comment]
Hey all. I just remade/refactored/wrote a library which also supports NZ https://github.com/iloveicedgreentea/jvc_projector_improved

There is also a home assistant component here. https://github.com/iloveicedgreentea/jvc_homeassistant

Both tested on my NZ7 just make sure you have your password set on your NZ first.

Hopefully it helps you out.

**Comment by bezmi** [comment]
This is fixed in the develop branch (big changes being worked on) but I am merging as a bugfix and will release a new version of the master branch.

**Pull request merged**
