### PR TITLE
Low latency mode

### PR DESCRIPTION
**Pull request by sledmonkey**
Added low latency feature that is supported in the NX series.

### CODE REVIEW

**Comment by bezmi** [comment]
Thanks for the contribution, could you explain the feature to me? If it replaces regular on/off I might have to add some logic to the homeassistant plugin which uses this library to utilise these commands for newer projectors.

**Comment by sledmonkey** [comment]
Low Latency mode is like a game mode you’d find on receivers or TVs. When it’s enabled it does less processing to lower the latency of the picture being displayed.  These codes don’t turn the projector on or off, so shouldn’t need to rework anything else. For more clarity however maybe should use enabled/disabled?

**Comment by bezmi** [comment]
Of course. I totally misunderstood on/off to mean power on/power off. Let's blame the lack of morning coffee. Yes, I do think enable/disable is better wording.

**Comment by sledmonkey** [comment]
Perfect, updated.

**Pull request merged**
