### PR TITLE
Added two picture mode commands (HDR and Cinema)

### PR DESCRIPTION
**Pull request by atrus05**
2 Picture mode commands added.
This is basically my first pull request, so please be careful when checking this out :)

### CODE REVIEW

**Comment by bezmi** [comment]
Awesome, looks like it should work. Have you tested on your X5900? You can see [here](https://github.com/bezmi/jvc_projector/blob/master/README.md#usage) for an example.

**Comment by atrus05** [comment]
I have not, as I do not have Home Assistant yet. I wanted to know if things like this would work before reworking my infrastructure around HASS. But I have tested it using a python script instead, which I call via Apple Shortcuts. So I can tell Siri to turn the projector on, and also off, and now to switch over to Cinema, and HDR mode. Which is pretty sweet.
I will most likely install HASS in the future as I now know this is a project that is maintained, and which I now know a little about. And even contributed to (even though at a miniscule level) :)

**Comment by bezmi** [comment]
You don't need homeassistant to use this, you can just follow the example i linked above and type the commands into the python interpreter. I will test it later tonight, so no hurry.

**Comment by atrus05** [comment]
Finally got around to test it this weekend, and my changes work just fine with your standalone solution. So it is now tested and you should be able to merge.

**Comment by bezmi** [comment]
Done. Will be putting out a new release of the python package relatively soon.

**Pull request merged**
